### ISSUE TITLE
[django] reverse routing

### ISSUE THREAD

**Issue by rsalmaso** [pmontrasio/rubynights-20170301#1]
Il supporto per dotted python path per ricavare le url è stato deprecato (e quindi non menzionato) diverse release fa e rimosso completamente dalla 1.10.
Il metodo corretto è usare i nomi https://docs.djangoproject.com/en/1.10/topics/http/urls/#naming-url-patterns

**Comment by pmontrasio** [comment]
Avrò un bel po' di URL da sistemare passando alla 1.10 :-(

Ho cambiato l'esempio con la [master 21ef9fb]

**Comment by rsalmaso** [comment]
Passa alla 1.11 (appena uscita la beta), futura LTS dopo la 1.8. Stando alla roadmap se qualcosa non è deprecato nella 1.11 funzionerà fino alla prossima LTS compresa (la 2.2) - a meno che non sia un comportamento errato.
