### ISSUE TITLE
Iteratori

### ISSUE THREAD

**Issue by keobox** [pmontrasio/rubynights-20170301#12]
In Python le liste non hanno un metodo iteritems.
Se la variabile "list" è un dizionario ti consiglio di chiamarlo "a_dict".
In Python3 si può usare il metodo items(), che restituisce un iteratore.

**Comment by cstrap** [comment]
Aggiungo che per i dizionari il for agisce sul primo iterable, quindi sulle chiavi:

```
d = {'ciao': 'ruby', 'hello': 'python'}

for e in d:
    print(e)

ciao
hello

for e in d:
    print(d[e])

ruby
python

for k, v in d.items()
    print("{} => {}".format(k, v))

ciao => ruby
hello => python

```

**Comment by pmontrasio** [comment]
Giusto, era un dict. Grazie.
 
Ho aggiunto l'esempio mancante [master 6719e64] [master 9750705]
