### ISSUE TITLE
Sintassi e whitespace

### ISSUE THREAD

**Issue by keobox** [pmontrasio/rubynights-20170301#13]
In Python il whitespace non è un problema, in Ruby [si](http://lucumr.pocoo.org/2008/7/1/whitespace-sensitivity/).

**Comment by pmontrasio** [comment]
Link interessante, grazie. Lo metto tra i WAT.

Il primo esempio è normale, conseguenza delle parentesi opzionali. Normale ma patologico, perché bisogna essere un po' sconsiderati per chiamare un array o hash con lo stesso nome di un metodo :-)

Al secondo caso non avevo pensato, ma odio scrivere ```foo/bar``` tutto attaccato. In qualsiasi linguaggio per leggibilità separo sempre in ```foo / bar```. Dev'essere per questo che non mi è mai capitato.

[master cbb850e]

**Comment by keobox** [comment]
Il punto che volevo far emergere e' che in Python il whitespace e' veramente significativo solo per i blocchi di codice. Non e' significativo per tutte le altre situazioni.

posso scrivere

print("hello world")

oppure

print ( "hello world"     )

e' sempre codice valido.
