### ISSUE TITLE
Funzioni

### ISSUE THREAD

**Issue by cstrap** [pmontrasio/rubynights-20170301#17]
data la funzione:

```
def funzione(arg1, arg2=None, arg3=None):
   ...  # le ellipiss sono codice valido in Python 3 


funzione(1)  # parametro obbligatorio
# arg2 e arg3 sono opzionali
funzione(1, arg2=2, arg3=2) 
funzione(1, arg3=2)
funzione(1, arg2=2)

```

Per simulare la stessa cosa di Ruby si potrebbe definire una funzione tipo:

```
def func(arg1, **kwargs):
    arg2 = kwargs.pop('arg2', None)
    arg3 = kwargs.pop('arg3', None)
    ... # do something

func('func', arg3='foo')
```

**Comment by pmontrasio** [comment]
Sì, ma da Ruby 2.0 ci sono i keyword argument, che pochi usano. Dev'essere per la stessa ragione per cui non tutti sanno che Python ha l'operatore ternario dalla 2.5.

La sintassi che proponi esiste in Ruby ma è adatta ad un altro caso. Lo spiego in master f1c7870

**Comment by cstrap** [comment]
Tra l'altro l'operatore ternario, prima della 2.5, può essere simulato con una tupla:

```
>>> ('false value', 'true value')[True]
true value
>>> ('false value', 'true value')[False]
false value
```

Just for fun :-)

**Comment by rsalmaso** [comment]
mi lascia un pochino perplesso questo 

> Inoltre forse è arrivato un po' tardi perché un paio di mesi fa lo sviluppatore Python a capo di uno dei progetti che seguo mi aveva detto che Python non ha un operatore ternario. Quando si impara che una cosa non esiste, poi non la si cerca più.

sinceramente lo vedo scritto ovunque nel codice esterno da un bel po' senza doverla cercare (la 2.5 è uscita il 19 settembre _2006_), quindi non saprei come commentare 🤔

**Comment by pmontrasio** [comment]
Ho fatto un grep nel codice e ne ho trovato qualcuno. Secondo me il senso di quello che mi aveva detto poteva essere che data la sintassi non l'aveva ricosciuto come operatore ternario ma come una forma compatta di if then else. In effetti Ruby e tanti altri linguaggi avrebbero due operatori ternari

```
a = cond ? caso_true : caso_false
b = if cond
         caso_true
      else
         caso_false
      end
```

Oppure mi stava semplicemente dicendo che Python non ha la consueta forma ```? :``` ma quella "lunga" con if the else e io ho frainteso.

**Comment by rsalmaso** [comment]
Ok
