### ISSUE TITLE
if elif else

### ISSUE THREAD

**Issue by cstrap** [pmontrasio/rubynights-20170301#19]
One rule to bring them all.
Non facendo pattern matching credo che sia stato semplificato, by design, non avere uno statement `switch`.

L'idea era quella di mantenere un numero minimo di parole chiave per il linguaggio e sono queste:
https://docs.python.org/3.5/reference/lexical_analysis.html#keywords

Nulla vieta che si possa scrivere :-)

Tra l'altro per eliminare gli `if` ci sono varie tecniche, combinando `any` o `all` a seconda dei casi.

**Comment by cstrap** [comment]
Oltre ai dizionari si potrebbe scrivere:

```
def func0(arg):
   ...
def func1(arg):
  ...

i_want_func = 'func1'
globals()[i_want_func]()
```

Ma la valanga di `if` o l'utilizzo improprio degli strumenti a disposizione del linguaggio fanno emergere un cattivo design dell'applicazione che si sta scrivendo.

**Comment by cstrap** [comment]
Dimenticavo, esistono pure  `eval()` e `local()` "to the rescue" (sono ironico qui :-) )

**Comment by cstrap** [comment]
Oppure in ottica object oriented, una classe che racchiude le varie condizioni:

```
class A():
    def method(self):
        print 'called'

getattr(A(), 'method')()
```

Wrappata in un `try except` giusto perche` siamo in ottica EAFP.

Martelli lo spiega molto bene: https://books.google.it/books?id=JnR9hQA3SncC&pg=PA134&lpg=PA134&dq=lbyl+vs+eafp+python+martelli&source=bl&ots=Jc9YHs232w&sig=u-fxbtQHb3o2td2DTjTp3XhyP7s&hl=it&sa=X&ved=0ahUKEwiykKPlopfSAhXGzRoKHUE8CRYQ6AEIMTAD#v=onepage&q=lbyl%20vs%20eafp%20python%20martelli&f=false

Anche questa e` una caratteristica di Python.
Non ho idea quale sia il metodo per gestire le eccezioni in Ruby... in Elixir e` facile... "let it crash"

**Comment by cstrap** [comment]
`getattr(object, value, default)` spesso è usato per i settings di Django.
Come vedi c'è il default, quindi non serve il catch dell'eccezione.
Tra l'altro va ricordato che gli oggetti di Python possono essere rappresentati come `dict`.
Il tuo esempio pythonico, a mio avviso, è più orientato al `getattr` anziché al `dict'.

**Comment by cstrap** [comment]
http://www.diveintopython.net/power_of_introspection/getattr.html

Tra l'altro in Python 3 c'è un decoratore per il dispatch: https://docs.python.org/3/library/functools.html#functools.singledispatch
Anche in questo caso sarebbe bello vedere come si comportano Ruby ed elixir.

**Comment by pmontrasio** [comment]
Aggiungo il tuo esempio con la commit master 727b458

Ruby ha più keyword di Python. A https://docs.ruby-lang.org/en/2.4.0/keywords_rdoc.html ne ho contate 41 contro le 33 di Python 3.

Non tutti sanno che le keyword di Ruby non sono parole riservate e si possono riusare, il che è bizzarro. Può darsi che occasionalmente sia utile ma ne farei a meno.

```
class Wierdo
   def if(cond)
     puts cond
  end
end
w = Wierdo.new
w.if true
# true
```

Python invece
```
def if(cond):
  File "<stdin>", line 1
    def if(cond):
         ^
SyntaxError: invalid syntax
```

e mi sembra meglio.

Eccezioni:

Una ```safe_divide_2(x, y)``` in Ruby sarebbe

```
def safe_divide_2(x, y)
  begin
     x / y
  rescue ZeroDivisionError
    puts "Attempted division by 0"
    nil
  end
end
```

o più succintamente

```
def safe_divide_2(x, y)
   x / y  rescue puts "Attempted division by 0" and return nil
end
```

che per una minor lunghezza ci consegna anche una peggior chiarezza.
