### ISSUE TITLE
[django] regex

### ISSUE THREAD

**Issue by rsalmaso** [pmontrasio/rubynights-20170301#2]
Le regex sono molto comode e tutto sommato molto potenti.
Però in effetti si sta valutando di introdurre un tag aggiuntivo a `url()` con una sintassi semplificata ispirata a flask DEP201 https://github.com/django/deps/blob/master/draft/0201-simplified-routing-syntax.rst

**Comment by pmontrasio** [comment]
Aggiunto esempio in [master 57b78f4]

**Comment by rsalmaso** [comment]
In realtà sarebbe così

```
from app import views

urlpatterns = [
    ...
    url(r'info/detail/(?P<id>[0-9]+)$', views.DetailView.as_view(), name='detail'), # in caso di CBV
    #url(r'info/detail/(?P<id>[0-9]+)$', views.detail_view, name='detail'), # in caso di funzione
    ...
]
```

e poi lo usi
`<a href="{% url 'detail' id %}" target="_blank" rel="noopener noreferrer">{{ label }}</a>`

In pratica a `url`, e `reverse`, passi il `name`.

(nota: un \' dopo `app.views.detail` riga 115 e usato in `{% url ... ` il dotted python path)

**Comment by pmontrasio** [comment]
Aggiunto l'esempio e risolto il bug degli apici mancanti [master 041a847]
