### ISSUE TITLE
Underscore

### ISSUE THREAD

**Issue by cstrap** [pmontrasio/rubynights-20170301#20]
A parte il riferimento nell'orm di django che e` opinabile, mi focalizzerei sul dato utilizzo di underscore singolo e doppio nel linguaggio.

L'utilizzo degli underscore e` stato introdotto anche per i numerici con la [PEP 515](https://www.python.org/dev/peps/pep-0515/): Underscores in Numeric Literals

Il doppio underscore e` utilizzato per i metodi speciali (`__init__`, `__iter__`, `__new__`...), vedi https://docs.python.org/3.5/reference/datamodel.html

Il singolo underscore per una proprieta` o metodo o funzione (in un modulo o package) indica che l'entita` e` privata, ma essenzialmente lo sa solo lo sviluppatore, per convenzione.
Infatti, Python non ha il concetto di `private` come in Java, quindi tutto e` pubblico.
Il doppio underscore di una proprieta` o metodo indica che e` privato e non accessibile fuori dalla classe. 
Qui entra in gioco il name mangling: https://docs.python.org/3.5/tutorial/classes.html#private-variables

Questi argomenti sarebbe bello vedere come vengono trattati in Ruby ed Elixir

**Comment by pmontrasio** [comment]
L'underscore come separatore di cifre per migliorare la leggibilità dei literal numerici è usato anche in Ruby

```
decimal = 10_0000
 => 100000 
binary = 0b10_0000
 => 32 
hex = 0x10_0000
 => 1048576 
```

Mi piace poco l'uso esteso che ne fa Python negli altri contesti perché è poco grazioso e poco leggibile. Al voltar di decennio tra gli '80 e i '90 sono stato felice di abbandonare tutti quei sotterfugi stilistici (lasciameli chiamare così) che usa il C per girare attorno alle carenze del linguaggio. Mi spiace ritrovarli 25 anni dopo, quando ci sono così tanti linguaggi che riescono a farne a meno. Le radici di Python sono piantate proprio negli anni '80 e quindi bisogna farsene una ragione. Anche il C non è cambiato. Però mi spiace che gli ORM Python usino la convenzione dei due underscore per passare da una tabella all'altra: è un po' opaca.

I metodi speciali non esistono in Ruby, è compito delle singole classi ereditare o importare un metodo, oppure definirne uno proprio. Essendo un linguaggio solo ad oggetti e senza funzioni, credo che non sia mai venuto a nessuno il desiderio di fornire lo syntactic sugar di scrivere ```length(oggetto)``` anziché ```oggetto.length```. Sarebbe contro lo stile generale del linguaggio. Si adatta invece bene a Python.

Anche in Ruby tutto è pubblico. ```private``` è zucchero sintattico che l'interprete prova a far rispettare, ma non fino in fondo.

```
class Thing
   attr_accessor :name # oppure si definiscono a mano name=() e name()
   private
   def rename(name)
     self.name = name # oppure @name = name
   end
end
t = Thing.new
t.name = "cosa" # oppure t.name("cosa") ma non è idiomatico
t.name
# "cosa" 
t.rename("altra cosa")
NoMethodError: private method `rename' called for #<Thing:0x0000000128c4d0 @name="cosa">
t.send(:rename, "altra cosa")
t.name
# "altra cosa" 
```

Non ho idea di che meccanismo usi Ruby per conservare i metodi originali sovrascritti da una sottoclasse. Provo:

```
class Person
   attr_accessor :name, :surname
   def fullname=(name_and_surname)
     @name, @surname = split(name_and_surname, " ")
  end
  def split(name_and_surname, separator)
     name_and_surname.split(separator)
  end
end

class Developer < Person
  def split(name_and_surname)
     name_and_surname.split("/")
  end
end

me = Person.new
me.fullname = "Paolo Montrasio"
me.name
# "Paolo" 
me.surname
# "Montrasio" 
dev = Developer.new
dev.fullname = "Paolo Montrasio"
# ArgumentError: wrong number of arguments (given 2, expected 1)
#	from (irb):12:in `split'
#	from (irb):4:in `fullname='
```

Questo è normale. L'esempio Python nel link infatti salvava il metodo per non farselo sovrascrivere. Salvarlo così non funziona, anche se dimostra qualche funzionalità di metaprogrammazione di Ruby:

```
class Person
   attr_accessor :name, :surname
   def initialize
    @split = method(:split)
   end
   def fullname=(name_and_surname)
     @name, @surname = @split.call(@split, name_and_surname, " ")
  end
  def split(name_and_surname, separator)
     name_and_surname.split(separator)
  end
end

class Developer < Person
  def split(name_and_surname)
     name_and_surname.split("/")
  end
end
```

Si ha lo stesso errore.

Non saprei se si può fare, non mi è mai capitato. Ci penserò nei prossimi giorni. Intanto mi salvo un link
http://stackoverflow.com/questions/18448831/calling-method-in-parent-class-from-subclass-methods-in-ruby

**Comment by cstrap** [comment]
No, l'orm di django userà gli underscore, ma da quel poco che so di peewee e sqlalchemy no. Non mi sembra corretto generalizzare tutti gli orm di python fanno così.
E stai parlano con uno che gli orm non piacciono poi molto, anche se notevolmente comodi.

**Comment by cstrap** [comment]
Il mro (method resolution order) in python può essere alquanto ostico: http://sixty-north.com/blog/method-resolution-order-c3-and-super-proxies

Poi rileggendo il tuo commento, mi è venuto in mente che django (ad esempio i models) fanno largo uso dei descriptor: http://chimera.labs.oreilly.com/books/1230000000393/ch08.html#_discussion_124 (discussion 124, 125, 126)

**Comment by pmontrasio** [comment]
Ho riformulato con la commit master efc700f rendendo esplicito che si tratta solo dell'ORM di Django. D'accordo con le tue considerazioni sugli ORM. Nel mio caso quando le query si complicano, vado di SQL anziché provare a riscrivere con l'ORM. Tanto poi bisogna vedere l'SQL per capire se gira abbastanza veloce o no, e perché.
