### ISSUE TITLE
Dove sarà la action corrispondente?

### ISSUE THREAD

**Issue by cstrap** [pmontrasio/rubynights-20170301#21]
Riguardo alle views chilometriche, il problema si è risolto utilizzando le classi based views.
L'approccio a oggetti, anziché funzioni, permette di avere più granularità per i metodi HTML (post,get) e Django mette a disposizione una buona gerarchia di viste per le esigenze più comuni: edit, list ecc.
Sia CBV che funzioni possono convivere tranquillamente in un progetto.
Riferimento https://docs.djangoproject.com/en/1.10/topics/class-based-views/

Esiste un package di terze parti Django braces che amplia notevolmente le cbv https://github.com/brack3t/django-braces

Nota storica: le CBV non sono state accolte con euforia, ma poi sono state notevolmente rivalutate

DRF usa pesantemente le CBV e introduce molta magia in Django

**Comment by pmontrasio** [comment]
Aggiunte le class based view con la commit master 668d5cd

**Comment by rsalmaso** [comment]
Non accolte con euforia più che altro che le viste generiche sono molto articolate e se non hai la mappa ti ci perdi (difficile ricordartele a memoria), non per l'idea di usare una classe (che invero aiuta moltissimo la personalizzazione se implementata bene).
Personalmente di solito mi fermo a `django.views.View` e implemento le mie `get` e `post`.
