### ISSUE TITLE
Costi al committente

### ISSUE THREAD

**Issue by cstrap** [pmontrasio/rubynights-20170301#23]
Manca il contesto.
Il progetto ROR, Django, web2py è capitato?
Lo si è cercato? Il committente si è rivolto alla mia azienda e ho venduto competenze che al momento non ho ma che potenzialmente sono interessato ad avere? (Questo giustificherebbe la fatica, ma non il costo da far gravare sul cliente)
Parti da un "Green field"? Chi me lo fa fare di utilizzare qualcosa di nuovo se vado fuori budget? È il cliente che lo chiede?

Solo alcune delle domande, direi che qui bisognerebbe essere più espliciti.

**Comment by pmontrasio** [comment]
Si tratta di questa sezione vero?

> Ogni progetto avrà le sue convenzioni e le sue eccezioni. Questo porta via tempo e costa soldi al cliente che paga a giornate. Oppure riduce il profitto dello sviluppatore che fa offerte a corpo, a meno che non chieda più soldi al cliente. Ma questo lo mette a rischio di perdere le offerte contro chi propone progetti Rails.

Tutti i progetti Python a cui ho lavorato sono stati ereditati. Quelli Rails su cui ho lavorato sono stati in parte ereditati e in parte scritti da me, da solo o con collaboratori che mi sono scelto.

La mia impressione è che con Python necessariamente si scrive più codice, a pari livello di abilità. E più codice equivale a più tempo e più tempo equivale a più soldi. Non posso dare né una prova matematica (anche se le import...) né una pratica perché per poter pareggiare le mie abilità Ruby e Python avrò bisogno di parecchi anni di Python e di far declinare un po' quelle Ruby (cosa che tra l'altro mi spiacerebbe ma prima o poi tutto passa, nel nostro lavoro più prima che poi).

@cstrap Da qui come si prosegue?

**Comment by cstrap** [comment]
Il punto è quello. A questo punto è una questione molto personale, in base ai progetti affrontati.
Io ho visto progetti django che sembravano spaghetti e lasagne code, altri invece molto puliti.
Purtroppo non ho le competenze in Ruby per avere un'opinione sul si scrive poco o tanto.
Le import, a cui tu dai molta importanza, sono una caratteristica del linguaggio, che può piacere o meno e... a te non piace :-)
Vero, alla luce di questo fatto si scrive di più, ma qui non voglio entrare nel tunnel del "io uso un ide, vim, emacs, che mi fa gli import via shortcuts", mi sembra la classica scusa di chi vuol accendere flame, quindi non lo farò... o l'ho fatto? :-D

**Comment by cstrap** [comment]
Dal mio personale punto di vista, dipende dal progetto. Non credo che scrivere un import in più o meno si vada fuori budget. Si va fuori budget se per risolvere un problema ci vuole più del previsto.
A meno di non praticare tutte quelle belle "agile rules", tipo scrum, xp, tdd, ddd ecc, ma mi spiace, finora non le ho mai viste funzionare e i budget sempre in erosion.
Anche in Java si scrive di più, ma i ragazzi in Pivoltal, che io sappia, bucano poco le scadenze, se non tendenti a zero. Forse perché da loro funziona il giro :-)

Perdonami, ma lo scrivere poco o più codice, la sintassi è più bella ecc, a mio avviso, sono poco costruttive. Concordo che i pareri personali ci siano in una presentazione, anche perché, come giustamente dici, il livello di esperienza nei vari linguaggi richiede tempo.

Elixir a me non piace, preferisco la sintassi considerata malata di erlang. Mi perdo tutto il discorso di macro e dsl che mi dà elixir? Sì, pazienza. Probabilmente prima di arrivare ad elixir ed erlang, passerò per cython, numba, uvloop per ottimizzare la mia applicazione, fino ad arrendermi.
Queste considerazioni le puoi fare solo se lavori su un prodotto (gestionale, crm...), mentre per un API rest o il sito della rosticceria o blog o qualsiasi altra cosa... magari mi posso anche piegare a php, massima resa, minor sforzo. Sto andando OT, vero?

**Comment by pmontrasio** [comment]
Non tanto.

Io credo che quando si lavora ad un proprio prodotto su cui si pensa di andare avanti per anni o tutta la vita, si può scegliere il linguaggio ed il framework in base a considerazioni di lunga durata (senza trascurare che se da zero al primo cliente passa troppo tempo la durata sarà breve).

Quando si lavora per un cliente che non ha un team IT interno e sul progetto si avvicenderanno molti sviluppatori diversi nel corso degli anni, senza magari potersi passare le consegne, allora bisogna andare su qualcosa di standard, che tutti sapranno riconoscere istantaneamente. Strumenti che fanno risparmiare tempo permettono di abbassare le offerte e far prendere progetti. Nel caso del web più un framework è opinionato e meno tempo richiede entrare in un progetto. Se poi le sue opinioni non piacciono se ne userà un altro.

Per la questione delle ```import```, Ruby ha le ```require``` che sono altrettanto obbligatorie, ma Rails fa il ```require``` di tutto quel che trova per cui non c'è bisogno di scriverle. Si scrive il codice che serve senza pensare ad altro. Forse è poco ma è un attrito in meno.

Del confronto tra le macro Elixir ed Erlang non so molto. Un paio di mesi fa avevo perso tempo dietro a quelle Elixir e pensavo che quelle Erlang fossero identiche, ma non le ho mai usate.

**Comment by cstrap** [comment]
Al riguardo di framework da utilizzare con un team con diversi sviluppatori: Matteo Vaccari, in una delle sue presentazioni, disse che non servono framework e che quello che serve può essere costruito in casa. Questo molto sommariamente, il talk se non ricordo male era di un'ora. 
Il pregio è che non sei legato a nessuna libreria/framework particolare, ma solo al linguaggio; significa che chi arriverà, dovrà avere "solo" la conoscenza del linguaggio, poiché il software sviluppato non è legato a logiche di framework particolari, ma solamente a quelle di dominio, rendendo di fatto uno "standard" la conoscenza del linguaggio.
Mi sembra una posizione sufficientemente estrema :-)

Btw, concordo con te che sui vari strumenti che fanno risparmiare tempo. 

Riguardo alle opinioni... qui è opinabile, perché dipende da quanto sei stato disposto ad investire per risparmiare tempo e come tu mi insegni, tempo, lo sviluppatore, ne ha sempre meno, molto meno e meno degli anni scorsi (questa me la rigioco sempre... era la risposta di un mio CTO riguardo al debito tecnico).
Infatti, se chiedi a me, ti dirò che Django è la soluzione a tutti i miei problemi e se chiedono a te, probabile che la risposta sia Rails :-)
L'utilizzo di un framework o un altro, dipende anche da quanto si è legati, di fatto django o rails potrebbero diventare legacy e i pezzi nuovi saranno scritti in altro linguaggio con tanto hype al momento, visto che posso trovare agilmente sviluppatori sul mercato. Da qui potrebbe partire la dismissione del legacy con "hype-language" per poi, nel giro di qualche anno (o forse meno), ritornare al punto di partenza.
