### ISSUE TITLE
Patterns

### ISSUE THREAD

**Issue by cstrap** [pmontrasio/rubynights-20170301#24]
MVC: ROR e web2py
MVT: Django 
Direi che due parole si possono fare, giusto per entrare nell'ottica dei framework

**Comment by pmontrasio** [comment]
In realtà non ho ben capito la vera differenza tra l'MVT Django e l'MVC degli altri due framework. Mi sembra più una questione di nomenclatura che di sostanza. Alla fine il codice in ```views.py``` di Django fa esattamente quel che fa il codice dei controller di Rails e i template Django sono esattamente uguali alle viste Rails, a parte il linguaggio di templating più limitato. @cstrap riusciresti a scrivere tu una spiegazione della differenza tra MVT e MVC? Grazie.

A proposito, anche per Ruby c'è un linguaggio di templating con le restrizioni imposte da Jinja. Si tratta di  Liquid di Shopify http://shopify.github.io/liquid/ che per evidenti ragioni non vuole che i suoi clienti possano far girare potenzialmente di tutto sui propri server.

**Comment by cstrap** [comment]
Hai riassunto perfettamente la differenza.
Ho aggiunto questa issue per via che molti developers fanno dei patterns la loro ragione di vita, quindi era per accontentare pure loro.
Una questione puramente di stile, non di sostanza.

**Comment by pmontrasio** [comment]
Aggiunto con commit master 2f768ff
