### ISSUE TITLE
Blocks

### ISSUE THREAD

**Issue by cstrap** [pmontrasio/rubynights-20170301#25]
Ho rispolverato qualche link al riguardo:
http://stupidpythonideas.blogspot.it/2014/06/why-python-or-any-decent-language.html
http://mitsuhiko.pocoo.org/pythonruby.html
http://nicolas-lara.blogspot.it/2009/01/emulating-ruby-blocks-in-python.html
Non trovo il link più interessante, quello che simulava i blocchi di Ruby in Python, son passati quella decina d'anni e ho lasciato cadere le iscrizioni ai vari "read-it-later" tools :-)
Questo https://dzone.com/articles/python-vs-php-vs-ruby-detailed-comparison apparso di recente credo sia poco significativo, soprattutto per via che Python ha l'operatore ternario, introdotti dalla 2.5...

Sarebbe bello far vedere i context manager di Python e l'equivalente in Ruby & C.

È un "prato fiorito" quello del confrontare linguaggi! :-)

**Comment by pmontrasio** [comment]
Aggiunta commit sull'operatore ternario, che non sapevo esistere in Python (mi avevano detto che non c'è) master 30c5539

I context manager sono questi?

https://jeffknupp.com/blog/2016/03/07/python-with-context-managers/
```
with open('what_are_context_managers.txt', 'r') as infile:
    for line in infile:
        print('> {}'.format(line))
```

In Ruby si fa così, usando i blocchi e la cooperazione della classe File che ha un costruttore che accetta un blocco e un enumeratore (perché usa la classe Enumerator, sarebbe un iteratore Python) che ritorna le linee del file

```
File.open("file", "r") do |f|
  f.each do |line|
    puts line
  end
end
```

Ho aggiunto una commit master 95d98f2 con quegli esempi.

**Comment by cstrap** [comment]
@pmontrasio la classe Ruby `File` si occupa di chiudere il file o devi in qualche modo esplicitarlo?
I context manager sono quelli indicati nel link.

**Comment by pmontrasio** [comment]
La classe File chiude il file alla fine del blocco.
