### ISSUE TITLE
WATs?

### ISSUE THREAD

**Issue by cstrap** [pmontrasio/rubynights-20170301#26]
Dipende dal tono che vuoi usare per la presentazione, ma potrebbe essere divertente esaltare i WATs?
Ruby:
https://www.destroyallsoftware.com/talks/wat
Python
https://youtu.be/sH4XF6pKKmk

Molto interessante sarebbe inserire la gestione degli oggetti mutabili e immutabili (list, tuple, string ecc)

**Comment by pmontrasio** [comment]
Non ho ancora deciso come riassumere tutto nel tempo a disposizione, che sarà poco rispetto a tutto il materiale che stiamo mettendo insieme. Ho inserito i link con la commit [master 189cedc]

Riguardo la mutabilità e i tipi di oggetti ho introdotto una commit con strutture dati di base e stringhe [master 0558c8a]

**Comment by cstrap** [comment]
Vero, il materiale è molto.
Tra l'altro i `dict` dalla versione 3.6 di Python sono ordinati e le performance di lookup sono migliorate.

Vedo che utilizzi `map`, anche in Python esiste, come anche altre funzioni quali `filter` e `reduce` che sono più leggibili della list comphrension. Assieme ai generatori sarebbe altro materiale da discutere.
Quanti incontri scheduliamo? :-)

**Comment by pmontrasio** [comment]
Bisognerebbe fare in uno :-)

Hanno migliorato le performance di lookup degli hash anche in Ruby 2.4. Chissà se è una coincidenza
https://blog.heroku.com/ruby-2-4-features-hashes-integers-rounding#hash-changes

Gli elementi sono enumerati in ordine di inserimento.

Ho recepito i suggerimenti su map reduce nella commit master ff01b66

**Comment by cstrap** [comment]
Direi che si può chiudere
