### ISSUE TITLE
Split & Join

### ISSUE THREAD

**Issue by keobox** [pmontrasio/rubynights-20170301#29]
Io questa sezione la toglierei. Lo dico spassionatamente: mi sembra un autogol per Ruby.
Per 2 motivi

1. Non capisco la maggiore consistenza di Ruby. E' perche' split e join sono entrambi metodi di Array? Solo che piu' sotto dici

In un lingua naturale, dove prevale il modo attivo avremmo
. separa "a.b.c"
. uniscisci ["a", "b", "c"]

In python scrivi proprio la seconda: . unisci la lista ["a", "b", "c"], in Ruby sei sul modo passivo su 2 casi (eh eh). Quindi Python e' 50% + naturale!

2. Andiamo un po' sul tecnico. La classe Array di Ruby ha 100 metodi! A me la classe Array di Ruby non mi sembra [S.O.L.I.D](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)).
Mi sembra che questa classe non rispetti molto la S e la I e faccia troppe cose. Mettere join sulle stringhe sarebbe stata una buona occasione per fargli fare una cosa in meno.

**Comment by pmontrasio** [comment]
Io invece la lascerei: se dovevo far vincere Ruby non vi avrei coinvolti, no? :-)

Sì, la consistenza è dovuta all'avere i due metodi nella stessa classe. Hai però ragione riguardo al modo attivo e passivo. Se non altro l'avevo indicato correttamente nei commenti del codice. Ho espanso la sezione con [master 167766a] che termina con una vera sorpresa.

Array (e non solo) ha davvero tanti metodi. Alcuni sono alias di altri e si dovrebbero sfoltire, altri equivalgono a costrutti Python separati come ad esempio le comprehension. Sono certo che qualsiasi cosa faccia Array di Ruby si faccia anche in Python, con metodi o funzioni varie. Il tuo punto è che andrebbe divisa in blocchi più piccoli. Perché no? Tenere tutto insieme però ha il vantaggio di non dover tenere a memoria decine di classi sorelle come si fa in Java. Ok, in Java il proliferare delle classi è dovuto anche allo static typing.

Andando a vedere Array ho scoperto il metodo [```cycle```](https://ruby-doc.org/core-2.4.0/Array.html#method-i-cycle) di cui ignoravo l'esistenza (ogni tanto mi capita) che si può implementare in puro Ruby. Di solito metodi come questi esistono per ragioni di performance: restando tutto dentro il sorgente C dell'interprete si guadagna qualcosa rispetto al loop Ruby. Forse è così:

```
$ ruby
require 'benchmark'

a = [1, 2, 3, 4]
loops = 10_000_000

Benchmark.bm do |x|
    x.report do
      a.cycle(loops) { |n| n }
    end
end

Benchmark.bm do |x|
    x.report do
      loops.times do
        a.each { |n| n }
      end
    end
 end
       user     system      total        real
   1.260000   0.010000   1.270000 (  1.273383)
       user     system      total        real
   1.740000   0.000000   1.740000 (  1.739497)
```

E' circa quello che [scriveva](http://www.onlamp.com/pub/a/python/2002/06/04/guido.html?page=2) Van Rossum di Python: "Beginners write Python modules, advanced developers can write extensions in C or C++ to make Python do things that it can't do out of the box". Non so però se intendeva anche riscrivere in C codice Python per farlo andare più veloce. Immagino che ci siano estensioni di quel tipo.
