### ISSUE TITLE
[django] urls.py

### ISSUE THREAD

**Issue by rsalmaso** [pmontrasio/rubynights-20170301#3]
In realtà le urls.py sono di ogni singola applicazione, danno una mappatura preconfigurata da poter utilizzare direttamente. Se necessario è possibile anche non utilizzarlo e copiarlo all'interno dell'urls genitore e/o modificarlo.

**Comment by cstrap** [comment]
Ci sono package che vanno ad arricchire Django:
https://github.com/theY4Kman/flango
https://djangopackages.org/grids/g/url-routing/

Sono più o meno mantenuti e chiaramente sono una nuova dipendenza al tuo progetto.

**Comment by pmontrasio** [comment]
Mi hanno segnalato anche il REST framework.
La definizione delle URL va nella direzione di quelle RESTful di Rails ma la sintassi mi sembra molto complicata
http://www.django-rest-framework.org/api-guide/routers/

**Comment by rsalmaso** [comment]
I routers sono degli shortcuts preconfigurati.
Potresti scriverti le urls a mano, invece in certi casi se usi un'istanza del router hai già tutto pronto. Non è detto che vada bene, ma se lo è hai già una mappatura CRUD.
Sinceramente non la vedo complicata. Diversa si dalle regex (le nasconde!), ma niente di particolare. E non essendo lo standard (libreria esterna) non trovo sia un grosso problema. Infatti se vedi nella DEP delle url semplificate ci ragionano su molto, visto che una volta ufficializzato diventa difficile rimuoverle. Cosa molto più semplice per una libreria aggiuntiva.

Tra l'altro, io al momento non li ho mai usati, sempre scritto le urls direttamente.
