### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by cstrap** [pmontrasio/rubynights-20170301#31]
Piccola nota: `pdb` è nella standard library, non servono package. `ipdb` aggiunge funzionalità, ma di base potrebbe esser sufficiente `pdb` (se non è indispensabile l'auto completamento, giusto per citare una feature aggiuntiva).
Esistono pure delle versioni web, ne cito una che ho provato: [wdb](https://github.com/Kozea/wdb)

**Comment by pmontrasio** [comment]
Aggiunti con [master 7aa2c43]
