### ISSUE TITLE
Addirittura nei ringraziamenti! Onorato ma non è necessario! 😝

### ISSUE THREAD

**Issue by fusillicode** [pmontrasio/rubynights-20170301#34]
> Gianluca Randazzo, la mano dietro a tanti eventi a cui partecipo, tra cui Ruby Nights, e il contatto con Python Milano

Ma non è necessario Paolo! 😆

Se però vuoi proprio lasciarmi nei ringraziamenti lascia pure soltanto [fusillicode](https://twitter.com/fusillicode) 😉

**Comment by pmontrasio** [comment]
Fatto
