### ISSUE TITLE
switch

### ISSUE THREAD

**Issue by rsalmaso** [pmontrasio/rubynights-20170301#35]
Mi era sfuggito questo: lo switch è stato trattato nella [pep 3103](https://www.python.org/dev/peps/pep-3103/):

**Rejection Notice**
_A quick poll during my keynote presentation at PyCon 2007 shows this proposal has no popular support. I therefore reject it._

**Comment by pmontrasio** [comment]
Aggiunta nota con [master 98ede0f]
