### ISSUE TITLE
[django] orm

### ISSUE THREAD

**Issue by rsalmaso** [pmontrasio/rubynights-20170301#4]
L'ORM di django permette di specificare la tabella (o colonna) che deve essere usata, senza necessità di avere un 1:1 fra nome python e nome db.

**Comment by cstrap** [comment]
Inoltre visito che si parla di orm, vauterei i pro e contro nell'utilizzare o meno orm nativi Python che non necessitano di librerie c esterne quali peewee e il gluon di web2py.
Web2py credo sia stato il primo a componenti e ciascun componente poteva esser usato senza la  necessità di installarlo: prendi il codice è fai l'import.

Python ha una interfaccia per i db e ha al suo interno embedded SQLite.

Ruby? Esiste solo activerecord?

**Comment by cstrap** [comment]
Una cosa da evidenziare è la disponibilità di gemme e package per i linguaggi e qui si può "opinionare" sul fatto della dispersione

**Comment by pmontrasio** [comment]
C'è qualche altro ORM https://www.ruby-toolbox.com/categories/orm ma essendo il default di Rails ActiveRecord domina.

L'alternativa che va di più è Sequel. Qualche esempio della sintassi a http://sequel.jeremyevans.net/rdoc/files/doc/querying_rdoc.html

ActiveRecord permette di specificare il nome di tabella da usare 

```
class Product < ApplicationRecord
  self.table_name = "my_products"
end
```

Questo è necessario quando si interfacciano db già esistenti perché non adottano le convenzioni Rails.

Accedere a colonne con nome diverso da quello Ruby è possibile, basta sovrascrivere gli accessor creati da Rails. Non mi viene in mente uno scenario in cui abbia senso, neppure accedendo a db preesistenti.

E' invece comune cambiare i nomi delle associazioni, sia con i db preesistenti ma anche con quelli nati con Rails: ad esempio quando ci sono due foreign key che vanno da una tabella ad un altra (strutture ad albero, grafi, etc).

Uscendo dagli ORM propriamente detti ci sono poi quelli che interfacciano db non relazionali come ad esempio Mongoid per Mongo.db.

**Comment by pmontrasio** [comment]
Rileggendo il codice dei miei progetti Python vedo che anche l'ORM di Django ha dei default per nomi tabelle e colonne. Sono sovrascrivibili con https://docs.djangoproject.com/en/1.10/ref/models/options/ 

E' l'ORM di Web2py a far indicare ogni volta nome tabella e nome colonna.

Ho rivisto la sezione ORM con [master 261386a]

**Comment by rsalmaso** [comment]
Mi sembra ok :+1:
