### ISSUE TITLE
[django] applications

### ISSUE THREAD

**Issue by rsalmaso** [pmontrasio/rubynights-20170301#5]
Le applicazioni django non sono altro che dei "moduli" di linguaggio, generamente con una struttura standard `__init__.py` `admin.py` `apps.py` `models.py` `urls.py` `views.py` più o meno preconfigurata.
A livello di linguaggio sono delle semplici librerie. Non hanno nulla a che vedere con l'esecuzione.

**Comment by pmontrasio** [comment]
Finalmente ho creato un progetto Django da zero e ho capito cosa è per lui un'applicazione. 
Vedi 01025ba43df359931d57b933b2802af8be0bd36b

Per curiosità: capita di riusare intere applicazioni da un progetto all'altro?

**Comment by rsalmaso** [comment]
Per creare un progetto o app va bene quello che esprime il tutorial, ma nella realtà si usa più spesso una soluzione come [cookiecutter](https://github.com/audreyr/cookiecutter) che genera un progetto a partire da un repository. Ad es. per django esiste [cookiecutter-django](https://github.com/pydanny/cookiecutter-django) che configura molto meglio rispetto allo scarno template di base. Ma se lo si usa spesso poi uno si costruisce il proprio template con le proprie idee e le proprie configurazioni (ad es. il [mio](https://bitbucket.org/rsalmaso/cookiecutter-fluo-project) ).

**Comment by rsalmaso** [comment]
Riusare intere applicazioni? Decisamente si.
Personalmente ho l'abitudine di "dividere" le applicazioni in

- generica, che vive autonomamente da sola nella lib, dove metto le classi base e diversi hook per personalizzare l'uso
- dedicata al progetto, estendo l'app generica (tramite settings, appconfig o estendendo i modelli)

E riuso varie parti in diversi progetti.

**Comment by pmontrasio** [comment]
Fai un subrepository nell'applicazione generica, in modo da condividerlo tra progetti come se fosse un modulo pip / gemma ruby o duplichi il codice?

**Comment by rsalmaso** [comment]
No, niente subrepository, ma proprio pacchetti separati installabili tramite pip (tra l'altro in genere sono in licenza MIT - se miei - o originale se ereditati-customizzati).
Poi li configuro/estendo nel mio progetto, che in genere invece è "proprietario".
Inoltre tendo ad avere un repository di progetto monolitico con tutte le dipendenze, in modo che quando si fa il deploy non si debba scaricare altro (ma qui è un altro discorso ancora).
