### ISSUE TITLE
[django] views.py

### ISSUE THREAD

**Issue by rsalmaso** [pmontrasio/rubynights-20170301#6]
L'uso di views.py è una convenzione, è un modulo che include le viste (sia in formato funzione sia in formato classe). Nulla vieta di mettere le funzioni in altri moduli, dal momento che vengono richiamate esplicitamente da `urls.py` (che a sua volta è pura convenzione, infatti a volte si trova nomato diversamente).

**Comment by pmontrasio** [comment]
Sì, nel progetto Django a cui lavoro ho iniziato ad estrarre codice da views.py e a metterlo in altri moduli. Mi hanno anche segnalato le class based views ma adesso non ho tempo per un refactoring esteso.

Guardando il progetto di cui sopra, mi sembra che ```urls.py``` si possa cambiare variando le ```include``` dentro il file definito come ```ROOT_URLCONF```. Però mi guarderei bene dal farlo per non complicare la vita di chi dovesse mettersi a lavorare su software dopo di me. Quando un sistema ha degli standard è meglio rispettarli.

**Comment by rsalmaso** [comment]
Refactoring da function based a CBV? Le function non sono assolutamente state deprecate, solo le generiche preconfezionate lo sono state (più comodo customizzarle). Quindi se non hai necessità non devi usarle.

`include` pensalo come se fosse un import: dice di usare l'urlpattern nel modulo indicato. l'admin usa una property dell'istanza site (=> `admin.site.urls` e quindi trovi come esempio
```
from django.contrib import admin
...
urlpatterns = [
...
    url(r'^admin/', include(admin.site.urls))
...
]
...
```

Personalmente non ho mai avuto nessun problema ad usare `urls.py`, `auth_urls.py`, `api.py` `admin.site.urls` etc delle singole applicazioni.
Concordo che la `ROOT_URLCONF` di base sia ideale lasciarla come `urls.py`, più immediato. Però per i test mi capita anche di cambiarla e usare chessò `tests.urls`, ma li non è il default.

(nota che con le ultime versioni in questo caso diventa `url(r'^admin/', admin.site.urls)` dal momento che la dichiarazione dei namespace è cambiata e semplificata, ma non è molto rilevante in questo contesto)

**Comment by pmontrasio** [comment]
Farei class based solo per avere file del tutto separati l'uno dall'altro anche come logica. Non mi entusiasma un views.py con 100 righe di import all'inizio.

**Comment by rsalmaso** [comment]
Gusti, tutto sommato invece io preferisco essere esplicito (pure troppo alle volte).
Poi non è detto che con le CBV si debba usare un file per classe, personalmente decido in base a quanto diventa lungo il file (e ad altre euristiche che variano caso per caso).
