### ISSUE TITLE
focus

### ISSUE THREAD

**Issue by rsalmaso** [pmontrasio/rubynights-20170301#7]
Avevo capito che fosse un confronto fra linguaggi, non framework (che sono ancora più controversi dei linguaggi stessi perché introducono ulteriori livelli da comprendere/gestire).

**Comment by pmontrasio** [comment]
Devo necessariamente parlare di Rails, perché Ruby si usa quasi solo per quello. Parlando di Rails devo parlare anche di Django e Web2py, che sono le ragioni per cui da un anno uso Python, a parte una rapida puntata in Flask.

**Comment by rsalmaso** [comment]
Beh ma quindi questo è un limite di ruby ;)
Scherzi a parte, ok, va bene però come dimostra il papirone rischia di diventare molto lungo il discorso.

**Comment by pmontrasio** [comment]
Non credo sia un limite del linguaggio. E' che Ruby è rimasto più o meno chiuso in Giappone per 10 anni e poi all'improvviso il mondo l'ha scoperto per via di Rails. Di conseguenza utti quelli interessati a Ruby erano interessati al web e quindi nel mondo fuori dal Giappone è rimasto un linguaggio per il web e tecnologie affini.

**Comment by rsalmaso** [comment]
Esatto, è la stessa cosa che ho riscontrato già nel 2007 quando dovevo scegliere fra rails/ruby e django/python: python era molto più "mondiale" e usato in più ambiti, e alla fine ha vinto lui. (intanto andavo avanti a jsp... per poco ma...).
Poi poco altro. So che è uno dei linguaggi sysadmin ufficiali interni ad amazon (e *non* python), ma direi che come linguaggio generico python ha avuto più diffusione.

**Comment by pmontrasio** [comment]
Sì, Ruby è web e sysadm (chef, capistrano, puppet) per via della necessità di fare il deploy di applicazioni web su più server. Poiché il devop già programmava in Rails, si è scritto il tool in Ruby. Poi sono arrivati ansible e salt dai devop che programmano in Python.
