### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by keobox** [pmontrasio/rubynights-20170301#9]
Nella sessione **Routing** c'è scritto "Il passare o meno blocchi di codice come argomenti è forse la differenza principale tra i due linguaggi, che impatta maggiormente sulle possibilità espressive.È quello che rende Ruby ottimo per i DSL".
Ma anche nella sezione **Migrazioni DRY** c'è scritto "Il linguaggio che si usa non è importante, anche se Ruby è migliore di Python per i DSL".

C'è scritto _2 volte_ che Ruby è migliore di Python per i DSL e questo non è DRY.

**Comment by pmontrasio** [comment]
Ho eliminato il secondo nel corso di una delle commit con cui ho visto la parte sulle migrazioni.
Ci sono issue aperte sul routing a cui non ho ancora lavorato.
